<h2 class="mb32 fs-headline1 fw-bold lh-sm fc-dark">API Terms of Use</h2>
<section class="grid--cell">
    <h3 class="fs-subheading fc-dark fw-bold lh-xs">Accepting the Terms of Use</h3>
    <p class="fs-body2 lh-lg fc-medium">The Website application programming interfaces (the “API Services”) are a set of programming interfaces which allow you to programmatically query and connect to the Website Network. Applications (“Applications”) are code, programs or other interfaces which connect to the API Services. Please read these terms of use (“API Agreement”) carefully before using the API Services. By using or accessing the API Services, you agree to become bound by all the terms and conditions of this API Agreement as well as the <a href="">Website Terms of Service</a>. If you do not agree to all the terms and conditions of this API Agreement, do not use the API Services. Website reserves the right, at its discretion, to modify these API Terms of Use at any time by posting revised API Terms of Use. The API Services are accessed by You (“Subscriber” or “You”) under the following terms and conditions:</p>

    <h3 class="mt24 fs-subheading fc-dark fw-bold lh-xs">API Attribution</h3>
    <p class="fs-body2 lh-lg fc-medium">All Applications must ensure they visually indicate that the Website Network is the source of the content provided through the API Services. Applications which may in any way be indexed by search engines must adhere to all Attribution rules defined in the <a href="">Website Terms of Service</a>. For applications that lack access to web browsing services, simple text versions of URLs (instead of hyperlinks) will be sufficient. Exceptions to these attribution rules must be requested in advance of deploying any Applications.</p>

    <h3 class="mt24 fs-subheading fc-dark fw-bold lh-xs">Website Trademark and Brand Guidelines</h3>
    <p class="fs-body2 lh-lg fc-medium">Website logos, branding, and other copyrighted content returned by the API may be used unmodified for the purposes of identification. Other uses of Website Inc. content are subject to the <a href="">Website Trademark Guidelines</a>.</p>

    <h3 class="mt24 fs-subheading fc-dark fw-bold lh-xs">Termination</h3>
    <p class="fs-body2 lh-lg fc-medium">Website may terminate or suspend any and all access to API Services immediately, without prior notice or liability, if You breach any of the terms or conditions of this API Agreement. Upon termination of access, Your right to use the API Services will immediately cease. All provisions of this API Agreement which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, and limitations of liability. Termination of Your access to and use of the API Services shall not relieve you of any obligations arising or accruing prior to such termination or limit any liability which You otherwise may have to Website or the API Services, including without limitation any indemnification obligations contained herein.</p>
</section>